---
- name: Install base dependencies
  apt: pkg={{ item }} state=installed update-cache=yes
  sudo: yes
  with_items:
    - build-essential
    - git-core

- name: Create deploy user
  sudo: yes
  user: name={{ deploy_user }}
        home=/home/{{ deploy_user }}
        group=staff
        groups=sudo
        shell=/bin/bash

- name: Add authorized keys for deploy user
  sudo: yes
  authorized_key: user={{ deploy_user }}
                  key="{{ item }}"
  with_file:
    - public_keys/chris-macbookpro
    - public_keys/chris-desktop

- include: iojs.yml
