---
- name: Create repo destination
  file: path=/home/deploy/hubot_marshall
        state=directory
        owner=deploy
        group=staff
  sudo: yes

- name: Update code
  git: repo=git://github.com/chrismar035/hubot_marshall.git
       dest=/home/deploy/hubot_marshall/
       accept_hostkey=true
       version=master
  sudo_user: deploy

- name: Install app node dependencies
  npm: path=/home/deploy/hubot_marshall/
       state=latest
  sudo: yes

- name: Create .hubotrc file
  sudo: yes
  template: src=hubotrc.j2
            dest=/home/deploy/hubot_marshall/bin/.hubotrc
            force=yes
            mode=755
            owner=deploy

- name: Create daemon executable
  sudo: yes
  copy: src=daemon.sh
        dest=/home/deploy/hubot_marshall/bin/daemon.sh
        owner=deploy
        mode="u+rwx"

- name: Restart Hubot
  sudo_user: deploy
  command: bin/daemon.sh restart
  args:
    chdir: /home/deploy/hubot_marshall
