---
- name: Create repo destination
  file: path={{ bot_root }}
        state=directory
        owner={{ deploy_user }}
        group=staff
  sudo: yes

- name: Update code
  git: repo=git://github.com/chrismar035/hubot_marshall.git
       dest={{ bot_root }}
       accept_hostkey=true
       version=master
  sudo_user: "{{ deploy_user }}"

- name: Install app node dependencies
  npm: path={{ bot_root }}
       state=latest
  sudo: yes

- name: Create .hubotrc file
  sudo: yes
  template: src=hubotrc.j2
            dest={{ bin_dir }}/.hubotrc
            force=yes
            mode=755
            owner={{ deploy_user }}

- name: Create daemon executable
  sudo: yes
  copy: src=daemon.sh
        dest={{ bin_dir }}/daemon.sh
        owner={{ deploy_user }}
        mode="u+rwx"

- name: Restart Hubot
  sudo_user: "{{ deploy_user }}"
  command: bin/daemon.sh restart
           chdir={{ bot_root }}
